<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BanjarCaptchaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('banjar_captchas')->truncate();

        $data = [
            ['kata_banjar' => 'Banyu', 'arti_indonesia' => 'Air'],
            ['kata_banjar' => 'Ganal', 'arti_indonesia' => 'Besar'],
            ['kata_banjar' => 'Rancak', 'arti_indonesia' => 'Sering'],
            ['kata_banjar' => 'Bepander', 'arti_indonesia' => 'Bicara'],
            ['kata_banjar' => 'Supan', 'arti_indonesia' => 'Malu'],
            ['kata_banjar' => 'Bujur', 'arti_indonesia' => 'Benar'],
            ['kata_banjar' => 'Iwak', 'arti_indonesia' => 'Ikan'],
            ['kata_banjar' => 'Kuitan', 'arti_indonesia' => 'Orang tua'],
            ['kata_banjar' => 'Dangsanak', 'arti_indonesia' => 'Saudara'],
            ['kata_banjar' => 'Tapas', 'arti_indonesia' => 'Cuci'],
            ['kata_banjar' => 'Ampih', 'arti_indonesia' => 'Berhenti / Selesai'],
            ['kata_banjar' => 'Anum', 'arti_indonesia' => 'Muda'],
            ['kata_banjar' => 'Hanyar', 'arti_indonesia' => 'Baru'],
            ['kata_banjar' => 'Arap', 'arti_indonesia' => 'Harap / Mengira'],
            ['kata_banjar' => 'Awak', 'arti_indonesia' => 'Badan / Tubuh'],
            ['kata_banjar' => 'Ayungku', 'arti_indonesia' => 'Milik saya / Kepunyaan saya'],
            ['kata_banjar' => 'Baelang', 'arti_indonesia' => 'Bertamu / Berkunjung'],
            ['kata_banjar' => 'Bahindang', 'arti_indonesia' => 'Berkilau / Menyala terang'],
            ['kata_banjar' => 'Bakarah', 'arti_indonesia' => 'Bertengkar / Berselisih'],
            ['kata_banjar' => 'Bakul', 'arti_indonesia' => 'Keranjang anyaman'],
            ['kata_banjar' => 'Balajar', 'arti_indonesia' => 'Belajar'],
            ['kata_banjar' => 'Balik', 'arti_indonesia' => 'Kembali / Pulang'],
            ['kata_banjar' => 'Bapandir', 'arti_indonesia' => 'Berbicara / Mengobrol'],
            ['kata_banjar' => 'Barakat', 'arti_indonesia' => 'Berkat / Manfaat'],
            ['kata_banjar' => 'Batakun', 'arti_indonesia' => 'Bertanya'],
            ['kata_banjar' => 'Bauntung', 'arti_indonesia' => 'Beruntung / Mujur'],
            ['kata_banjar' => 'Bungas', 'arti_indonesia' => 'Cantik / Tampan / Rupawan'],
            ['kata_banjar' => 'Calap', 'arti_indonesia' => 'Tergenang air / Banjir dangkal'],
            ['kata_banjar' => 'Cangkal', 'arti_indonesia' => 'Rajin / Giat / Ulet'],
            ['kata_banjar' => 'Cucuk', 'arti_indonesia' => 'Cocok / Sesuai / Pas'],
            ['kata_banjar' => 'Cuntan', 'arti_indonesia' => 'Curi / Mencuri'],
            ['kata_banjar' => 'Daling', 'arti_indonesia' => 'Miring / Condong'],
            ['kata_banjar' => 'Gair', 'arti_indonesia' => 'Takut / Cemas / Khawatir'],
            ['kata_banjar' => 'Gancang', 'arti_indonesia' => 'Kuat / Bertenaga / Kencang'],
            ['kata_banjar' => 'Garit', 'arti_indonesia' => 'Gores / Cakar'],
            ['kata_banjar' => 'Guring', 'arti_indonesia' => 'Tidur'],
            ['kata_banjar' => 'Handak', 'arti_indonesia' => 'Mau / Ingin / Hendak'],
            ['kata_banjar' => 'Haram', 'arti_indonesia' => 'Diam / Tenang / Tidak berkutik'],
            ['kata_banjar' => 'Haur', 'arti_indonesia' => 'Sibuk / Banyak urusan'],
            ['kata_banjar' => 'Himung', 'arti_indonesia' => 'Senang / Gembira / Bahagia'],
            ['kata_banjar' => 'Inya', 'arti_indonesia' => 'Dia / Ia'],
            ['kata_banjar' => 'Jagau', 'arti_indonesia' => 'Jagoan / Pemberani'],
            ['kata_banjar' => 'Jaka', 'arti_indonesia' => 'Seandainya / Jikalau'],
            ['kata_banjar' => 'Jumbatan', 'arti_indonesia' => 'Jembatan'],
            ['kata_banjar' => 'Kada', 'arti_indonesia' => 'Tidak / Bukan'],
            ['kata_banjar' => 'Kaina', 'arti_indonesia' => 'Nanti / Sebentar lagi'],
            ['kata_banjar' => 'Kancang', 'arti_indonesia' => 'Erat / Kuat / Kencang'],
            ['kata_banjar' => 'Kawa', 'arti_indonesia' => 'Bisa / Sanggup / Mampu'],
            ['kata_banjar' => 'Ketuju', 'arti_indonesia' => 'Suka / Gemar / Senang'],
            ['kata_banjar' => 'Kiwa', 'arti_indonesia' => 'Kiri'],
            ['kata_banjar' => 'Kuyahi', 'arti_indonesia' => 'Memberi garam / Membumbui'],
            ['kata_banjar' => 'Lawas', 'arti_indonesia' => 'Lama / Kuno'],
            ['kata_banjar' => 'Lawang', 'arti_indonesia' => 'Pintu'],
            ['kata_banjar' => 'Lunuk', 'arti_indonesia' => 'Lembek / Lunak'],
            ['kata_banjar' => 'Mandi', 'arti_indonesia' => 'Mandi'],
            ['kata_banjar' => 'Maras', 'arti_indonesia' => 'Kasihan / Iba'],
            ['kata_banjar' => 'Mun', 'arti_indonesia' => 'Kalau / Jika'],
            ['kata_banjar' => 'Nang', 'arti_indonesia' => 'Yang (kata hubung)'],
            ['kata_banjar' => 'Nyaman', 'arti_indonesia' => 'Enak / Sedap / Nyaman'],
            ['kata_banjar' => 'Padah', 'arti_indonesia' => 'Beritahu / Bilang'],
            ['kata_banjar' => 'Paluh', 'arti_indonesia' => 'Keringat'],
            ['kata_banjar' => 'Pamalar', 'arti_indonesia' => 'Pelit / Kikir'],
            ['kata_banjar' => 'Pian', 'arti_indonesia' => 'Anda / Kamu (bentuk sopan)'],
            ['kata_banjar' => 'Rigat', 'arti_indonesia' => 'Kotor'],
            ['kata_banjar' => 'Rakat', 'arti_indonesia' => 'Rukun / Akur / Guyub'],
            ['kata_banjar' => 'Saing', 'arti_indonesia' => 'Saing / Bersaing'],
            ['kata_banjar' => 'Sambat', 'arti_indonesia' => 'Sebut / Ucapkan'],
            ['kata_banjar' => 'Sangkal', 'arti_indonesia' => 'Kesal / Jengkel / Gondok'],
            ['kata_banjar' => 'Sungsang', 'arti_indonesia' => 'Terbalik / Jungkir balik'],
            ['kata_banjar' => 'Tapih', 'arti_indonesia' => 'Sarung'],
            ['kata_banjar' => 'Tulak', 'arti_indonesia' => 'Berangkat / Pergi'],
            ['kata_banjar' => 'Ulun', 'arti_indonesia' => 'Saya / Hamba (bentuk santun)'],
            ['kata_banjar' => 'Unda', 'arti_indonesia' => 'Aku / Gua (ragam akrab)'],
            ['kata_banjar' => 'Wadai', 'arti_indonesia' => 'Kue tradisional'],
            ['kata_banjar' => 'Waluh', 'arti_indonesia' => 'Labu parang / Dusta (slang)'],
            ['kata_banjar' => 'Abut', 'arti_indonesia' => 'Ribut / Gaduh / Heboh'],
            ['kata_banjar' => 'Acan', 'arti_indonesia' => 'Terasi'],
            ['kata_banjar' => 'Ading', 'arti_indonesia' => 'Adik'],
            ['kata_banjar' => 'Ambin', 'arti_indonesia' => 'Teras / Serambi rumah'],
            ['kata_banjar' => 'Ampah', 'arti_indonesia' => 'Arah / Menuju ke'],
            ['kata_banjar' => 'Ampar', 'arti_indonesia' => 'Hampar / Membentangkan tikar'],
            ['kata_banjar' => 'Ancap', 'arti_indonesia' => 'Cepat / Lekas / Bergegas'],
            ['kata_banjar' => 'Andak', 'arti_indonesia' => 'Meletakkan / Menaruh'],
            ['kata_banjar' => 'Angsul', 'arti_indonesia' => 'Uang kembalian belanja'],
            ['kata_banjar' => 'Apik', 'arti_indonesia' => 'Rapi / Bersih / Cermat'],
            ['kata_banjar' => 'Aruh', 'arti_indonesia' => 'Kenduri / Selamatan / Pesta'],
            ['kata_banjar' => 'Asaan', 'arti_indonesia' => 'Canggung / Segan / Ragu-ragu'],
            ['kata_banjar' => 'Awit', 'arti_indonesia' => 'Awet / Tahan lama'],
            ['kata_banjar' => 'Baaci', 'arti_indonesia' => 'Bersiap-siap / Memulai sungguh-sungguh'],
            ['kata_banjar' => 'Baampik', 'arti_indonesia' => 'Bertepuk tangan'],
            ['kata_banjar' => 'Babaya', 'arti_indonesia' => 'Hampir / Nyaris / Bersamaan'],
            ['kata_banjar' => 'Badadas', 'arti_indonesia' => 'Bersegera / Terburu-buru'],
            ['kata_banjar' => 'Bagana', 'arti_indonesia' => 'Diam / Tinggal / Menetap'],
            ['kata_banjar' => 'Bahimat', 'arti_indonesia' => 'Bersungguh-sungguh / Sekuat tenaga'],
            ['kata_banjar' => 'Bahari', 'arti_indonesia' => 'Zaman dahulu / Kuno'],
            ['kata_banjar' => 'Baisukan', 'arti_indonesia' => 'Pagi hari'],
            ['kata_banjar' => 'Bajuang', 'arti_indonesia' => 'Berjuang / Bekerja keras'],
            ['kata_banjar' => 'Bakuliling', 'arti_indonesia' => 'Berkeliling / Memutar'],
            ['kata_banjar' => 'Balalah', 'arti_indonesia' => 'Bepergian / Merantau / Keluyuran'],
            ['kata_banjar' => 'Baluman', 'arti_indonesia' => 'Belum'],
            ['kata_banjar' => 'Bapara', 'arti_indonesia' => 'Mendekat / Menghampiri'],
            ['kata_banjar' => 'Bapicik', 'arti_indonesia' => 'Memijat / Menekan'],
            ['kata_banjar' => 'Barinjam', 'arti_indonesia' => 'Meminjam'],
            ['kata_banjar' => 'Basanga', 'arti_indonesia' => 'Menggoreng'],
            ['kata_banjar' => 'Basaruan', 'arti_indonesia' => 'Mengundang / Hajatan'],
            ['kata_banjar' => 'Batatapas', 'arti_indonesia' => 'Mencuci pakaian'],
            ['kata_banjar' => 'Baunggut', 'arti_indonesia' => 'Mengangguk-angguk'],
            ['kata_banjar' => 'Bini', 'arti_indonesia' => 'Istri / Perempuan'],
            ['kata_banjar' => 'Buhannya', 'arti_indonesia' => 'Mereka / Rombongan mereka'],
            ['kata_banjar' => 'Bungkar', 'arti_indonesia' => 'Bongkar / Membuka paksa'],
            ['kata_banjar' => 'Butah', 'arti_indonesia' => 'Buta / Tidak melihat'],
            ['kata_banjar' => 'Cangang', 'arti_indonesia' => 'Menatap / Memandang tajam'],
            ['kata_banjar' => 'Cangkar', 'arti_indonesia' => 'Keras / Kaku'],
            ['kata_banjar' => 'Cariu', 'arti_indonesia' => 'Nyaring / Melengking (suara)'],
            ['kata_banjar' => 'Cilum', 'arti_indonesia' => 'Menyelam'],
            ['kata_banjar' => 'Culik', 'arti_indonesia' => 'Mencolek / Mengambil sedikit'],
            ['kata_banjar' => 'Dalu', 'arti_indonesia' => 'Larut malam / Tengah malam'],
            ['kata_banjar' => 'Damini', 'arti_indonesia' => 'Sekarang / Masa kini'],
            ['kata_banjar' => 'Dingin', 'arti_indonesia' => 'Dingin / Sejuk'],
            ['kata_banjar' => 'Duduk', 'arti_indonesia' => 'Duduk'],
            ['kata_banjar' => 'Dusta', 'arti_indonesia' => 'Bohong / Tidak benar'],
            ['kata_banjar' => 'Gagah', 'arti_indonesia' => 'Kuat / Gagah perkasa'],
            ['kata_banjar' => 'Gani\'i', 'arti_indonesia' => 'Membantu / Menemani'],
            ['kata_banjar' => 'Garunum', 'arti_indonesia' => 'Bergumam / Menggerutu'],
            ['kata_banjar' => 'Gigi', 'arti_indonesia' => 'Gigi'],
            ['kata_banjar' => 'Gumbili', 'arti_indonesia' => 'Singkong / Ubi kayu'],
            ['kata_banjar' => 'Guyur', 'arti_indonesia' => 'Menyiram / Mengguyur air'],
            ['kata_banjar' => 'Halu', 'arti_indonesia' => 'Alu / Penumbuk padi'],
            ['kata_banjar' => 'Halus', 'arti_indonesia' => 'Kecil / Halus'],
            ['kata_banjar' => 'Hanta', 'arti_indonesia' => 'Tawar / Kurang rasa / Hambar']
        ];

        DB::table('banjar_captchas')->insert($data);
    }
}
